name: "Custom Env Vars"

on:
  workflow_dispatch:

env:
  DAY_OF_WEEK: Funday
  testvar: value-1

jobs:
  mainjob:
    name: "Print the env vars"
    runs-on: ubuntu-latest

    env:
      Greeting: Dear
      testvar: value-2

    steps:
      - name: Print values of env vars
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK"
          echo "testvar using shell: $testvar"
          echo "testvar using GitHub syntax: ${{ env.testvar }}"
        env:
          First_Name: Student
          testvar: value-3
